### ISSUE TITLE
[Feature] Increase Drop area

### ISSUE THREAD

**Issue by AMPZart** [pqina/filepond#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Is there a solution to increase the height of the drop area?
The question was raised on Stackoverflow...
[https://stackoverflow.com/questions/56813374/how-to-increase-dimensions-of-filepond-drop-area-in-react-js](url)
But I also notice that by increasing the size in the css : 
```css
.filepond--root,
.filepond--root .filepond--drop-label {
  height: 200px;
}
``` 
 the area no longer displays the downloaded images.
Thanks

### Describe the solution you'd like

The area is too small for my page

### Describe alternatives you've considered

A size of at least 200px would be suitable
