### ISSUE TITLE
CSS Crash with Buefy UI

### ISSUE THREAD

**Issue by y-za** [pqina/filepond#106]
Hallo,

this is nice library, but i found css crash with Buefy UI 😭

![](https://2.bp.blogspot.com/-0QsjcohUE3g/W3pjRNpDwpI/AAAAAAAAADQ/zMHQzIoc8JsQiK0bET7OnO4HJDwyDoJgwCLcBGAs/s1600/Image%2B40.png)

can anyone helpme 😔

**Comment by rikschennink** [comment]
I think indeed there might be a some style collisions but I'm also wondering if you've linked up the image preview CSS? If you didn't, can you do so and then post a new screenshot? A public test case would also be useful.

**Comment by y-za** [comment]
thx u, in this case i using Buefy v0.6.6
this is my css list

![](https://3.bp.blogspot.com/-GKCdFpL_vb4/W3pyx_PiozI/AAAAAAAAADk/bdPtLLDMveopTFmhf_b2lurgfvyLCaA-gCLcBGAs/s1600/Image%2B43.png)

i'm just clear my browser cache, and now work but how to fill this space?
![](https://4.bp.blogspot.com/-0GGlbadJYbw/W3pyH2WrKgI/AAAAAAAAADc/_GugLcwwDAEPr7eYauJ0jPiSE64K4-9AQCLcBGAs/s1600/Image%2B42.png)

**Comment by rikschennink** [comment]
I think something like this should fix it:

```css
.filepond--list
.filepond--item,
.filepond--file-wrapper {
  margin:0 !important;
  padding:0 !important;
}
```

**Comment by y-za** [comment]
this is no effect
```css
.filepond--list
.filepond--item,
.filepond--file-wrapper {
  margin:0 !important;
  padding:0 !important;
}
```
i just added this code for remove unordered lists from Buefy UI
```css
.content ul {
    list-style: none;
}
```
and finally i set the margin like this, in my case this look little bit better 😅

![](https://2.bp.blogspot.com/-kJcCJVLnyhE/W3qAZyZpSMI/AAAAAAAAAD8/KTVAtYF6a1sIew4L3u_A8WYYTspGxjBbgCLcBGAs/s1600/Image%2B45.png)
