### ISSUE TITLE
CSS Inheritance Issue

### ISSUE THREAD

**Issue by willpower232** [pqina/filepond#148]
### Summary

The default CSS isn't specific enough which means an innocent `*` can significantly reduce the readability.

It becomes a major problem when using [pqina/filepond-plugin-image-preview](https://github.com/pqina/filepond-plugin-image-preview) (probably because of https://github.com/pqina/filepond-plugin-image-preview/issues/7 and the SVG relying on `currentColor`) but I haven't tested other plugins to see if they have any similar issues.

### How to reproduce

Include the following anywhere in the page

```css
body * {
    color: #444;
}
```

### Expected behaviour

The page text is coloured in a light grey but filepond works normally as dictated by its stylesheets.

### Current behaviour

![image](https://user-images.githubusercontent.com/1619102/47254869-6f5abf80-d45f-11e8-96fa-0762fb2e8362.png)

(this is a completed upload with grey text on a grey gradient)

### Suggested resolutions

When the plugin relies on colours, the colours should either be applied directly to the elements or use an `*` to accomplish the same effect.

In filepond itself:

```css
.filepond--file * {
    color: #fff;
}
```

In the image preview plugin:

```css
.filepond--image-preview-overlay-idle svg * {
    mix-blend-mode: multiply;
    color: rgba(40,40,40,.85);
}
.filepond--image-preview-overlay-success svg * {
    mix-blend-mode: normal;
    color: #369763;
}
.filepond--image-preview-overlay-failure svg * {
    mix-blend-mode: normal;
    color: #c44e47;
}
```

### Additional information

I encountered this using filepond 3.1.4 with image preview plugin 3.0.0 (both sourced from the listed CDN) using Windows 10 and Firefox 62.0.3.

I have made local copies to include and test my fixes and they seem to be sufficient but I thought it was worthy of bringing to your attention before making pull requests.

Thank you for your time and excellent plugin.
