### ISSUE TITLE
[Suggestion] Add cursor: pointer; to the root element

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond#324]
Hello,

This is a suggestion to add a style `cursor: pointer;` to the root element.
Currently this is the default cursor, maybe it would be more intuitive to add this specific cursor in order to know that the user can click to add files!

Thanks!

**Comment by rikschennink** [comment]
The default file input doesn't show a pointer, I've copied this behaviour.

This CSS snippet adds the cursor and removes it for files in the file list.
```css
.filepond--root {
  cursor: pointer;
}

.filepond--list-scroller {
  cursor: default;
}
```
