### ISSUE TITLE
image preview overflow not working on safari

### ISSUE THREAD

**Issue by ikkez** [pqina/filepond#487]
Because of the preview image has a bunch of 3d transforms enabled, the overflow:hidden on the `.filepond--image-preview-wrapper` does not seem to work in safari on mac:

![Bildschirmfoto 2020-04-28 um 15 31 52](https://user-images.githubusercontent.com/1177647/80493832-32319080-8966-11ea-873e-e0a9c5e23f9c.png)

Adding this seems to solve the issue for me:

```css
.filepond--image-preview-wrapper {
  -webkit-mask-image: -webkit-radial-gradient(white, black);
}
```

Now correct:
![Bildschirmfoto 2020-04-28 um 15 32 29](https://user-images.githubusercontent.com/1177647/80493907-4ecdc880-8966-11ea-894f-6293dc537c8a.png)
