### ISSUE TITLE
"filepond--drop-label" displays over the picture sometimes

### ISSUE THREAD

**Issue by meness** [pqina/filepond#574]
**Describe the bug**
The element with `filepond--drop-label` class displays over the picture sometimes as you see on the image below.

![تنظیمات-پروفایل-Balcon-us](https://user-images.githubusercontent.com/7955356/94432056-092a5b80-01a3-11eb-8ba4-93a0a598f4e0.png)

**To Reproduce**
It's hard to say how to reproduce this bug, but I see it sometimes with the following configuration.

```jsx
<FilePond
      ref={ref}
      labelIdle='<span class="filepond--label-action"><svg /></span>'
      imagePreviewHeight={120}
      imageCropAspectRatio="1:1"
      stylePanelLayout="compact circle"
      className="avatar-img"
      allowDrop={false}
      allowPaste={false}
      labelMaxFileSizeExceeded="lorem ipsum"
      labelMaxFileSize="lorem ipsum"
      labelFileTypeNotAllowed="lorem ipsum"
      fileValidateTypeLabelExpectedTypes="lorem ipsum"
      iconUndo='<svg />'
      iconRetry='<svg />'
      iconProcess='<svg />'
      iconRemove='<svg />'
      styleButtonRemoveItemPosition="bottom right"
      styleButtonProcessItemPosition="bottom left"
      styleLoadIndicatorPosition="center"
      styleProgressIndicatorPosition="center"
    />
```

```scss
$activeColor: #377dff;

:global {
  .filepond--root {
    width: 120px;
    cursor: default;

    &[data-style-panel-layout~='circle'] {
      overflow: visible;

      .filepond--file [data-align*='right'] {
        right: 0;
      }

      .filepond--file [data-align*='left'] {
        left: 0;
      }
    }

    &.avatar-img {
      pointer-events: all !important;
    }
  }

  .filepond--drop-label {
    cursor: pointer;

    label {
      padding: 0 !important;
    }
  }

  .filepond--label-action {
    text-decoration: none;
  }

  .filepond--file [data-align*='bottom'] {
    bottom: 0;
  }

  .filepond--list-scroller {
    overflow: visible !important;
  }

  .avatar-uploader {
    &:hover {
      .filepond--file-action-button > svg:hover {
        background-color: $activeColor;
        color: white;
      }

      .filepond--label-action > svg {
        color: $activeColor;
      }
    }
  }

  .filepond--file-action-button {
    cursor: pointer !important;
    border-radius: 50% !important;
    margin: 0 !important;
    width: auto !important;
    height: auto !important;
    background: none !important;
    transition: none !important;
    box-shadow: none !important;

    &:after {
      display: none;
    }

    > svg {
      display: inline-flex;
      flex-shrink: 0;
      padding: 9px;
      justify-content: center;
      align-items: center;
      background-color: #fff;
      border-radius: 50%;
      transition: 0.2s;
      box-shadow: 0 3px 6px 0 rgba(140, 152, 164, 0.25) !important;
      color: #677788;
    }
  }

  .filepond--image-preview-overlay {
    display: none !important;
  }

  .avatar-xxl .filepond--file-action-button > svg {
    width: 2.1875rem !important;
    height: 2.1875rem !important;
  }

  .filepond--file,
  .filepond--file-wrapper,
  .filepond--item {
    margin: 0 !important;
    padding: 0 !important;
  }
}

```

**Expected behavior**
When the picture is loading (it may take time) the search icon get hidden, and only be displayed when there is no picture in process.

**Information about your project:**
I get this weird behavior with multiple devices and multiple browsers, including iOS, Android, Chrome, and Safari (all latest stable version)

- FilePond version: 4.20.1
- FilePond React version: 7.1.0
